name: Publish Application on GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  setup:
    name: "Upload secrets"
    runs-on: ubuntu-latest
    steps:
      - name: "Put secrets to properties"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        run: |
          echo -e "OPENAI_API_KEY=$OPENAI_API_KEY" > local.properties
          echo -e "SUPABASE_URL=$SUPABASE_URL" >> local.properties
          echo -e "SUPABASE_API_KEY=$SUPABASE_API_KEY" >> local.properties
      - name: "Upload properties"
        uses: actions/upload-artifact@v4
        with:
          name: local-properties
          path: local.properties

  build:
    name: "Build Kotlin/Wasm"
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Download properties"
        uses: actions/download-artifact@v4
        with:
          name: local-properties
          path: .

      - name: "Run Gradle Tasks"
        run: ./gradlew wasmJsBrowserDistribution

      - name: "Fix permissions"
        run: |
          chmod -v -R +rX "composeApp/build/dist/wasmJs/productionExecutable/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: "Upload Pages artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: composeApp/build/dist/wasmJs/productionExecutable/

  deploy:
    name: "Deploy to GitHub Pages"
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4